# Generated by Django 2.0.1 on 2018-01-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180116_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.PositiveIntegerField(),
        ),
    ]
