# Generated by Django 3.2.15 on 2022-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('prices', models.JSONField(default=dict)),
                ('name', models.TextField()),
                ('relative_url', models.TextField()),
                ('image', models.URLField()),
                ('delivery', models.TextField()),
                ('online', models.BooleanField()),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('is_customizable', models.BooleanField()),
                ('is_exclusive', models.BooleanField()),
                ('stock', models.JSONField(default=dict)),
                ('currency', models.CharField(max_length=5)),
                ('url', models.URLField()),
                ('attributes', models.JSONField(default=dict)),
            ],
        ),
    ]
