# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_customizable', models.BooleanField()),
                ('delivery', models.CharField(max_length=200)),
                ('kids', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('sizes', models.CharField(max_length=200)),
                ('kid_adult', models.BooleanField()),
                ('free_porto', models.BooleanField()),
                ('image', models.CharField(max_length=200)),
                ('package', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('url', models.CharField(max_length=200)),
                ('online', models.BooleanField()),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('img_url', models.CharField(max_length=200)),
                ('women', models.BooleanField()),
            ],
            options={
                'ordering': ('price',),
            },
        ),
    ]
