# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('kids', models.BooleanField()),
                ('price_old', models.FloatField()),
                ('name', models.CharField(max_length=500)),
                ('delivery', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('currency', models.CharField(max_length=3)),
                ('img_url', models.CharField(max_length=500)),
            ],
        ),
    ]
