# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('kids', models.CharField(max_length=1)),
                ('price_old', models.FloatField()),
                ('name', models.CharField(max_length=500)),
                ('is_customizable', models.CharField(max_length=1)),
                ('delivery', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=150)),
                ('kid_adult', models.CharField(max_length=1)),
                ('free_porto', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=500)),
                ('package', models.CharField(max_length=1)),
                ('url', models.CharField(max_length=500)),
                ('online', models.CharField(max_length=1)),
                ('currency', models.CharField(max_length=3)),
                ('img_url', models.CharField(max_length=500)),
                ('women', models.CharField(max_length=1)),
            ],
        ),
    ]
