# Generated by Django 4.0 on 2022-08-18 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("attributes", models.JSONField()),
                ("labels", models.JSONField(blank=True, default=list)),
                ("name", models.TextField()),
                ("relative_url", models.TextField(max_length=250)),
                ("image", models.URLField()),
                ("delivery", models.TextField(max_length=50)),
                ("online", models.BooleanField()),
                ("is_customizable", models.BooleanField()),
                ("is_exclusive", models.BooleanField()),
                ("url", models.URLField()),
                ("max_price", models.PositiveIntegerField()),
                ("min_price", models.PositiveIntegerField()),
                ("discount_percentage", models.PositiveSmallIntegerField(default=0)),
                ("recommended_retail_price", models.PositiveIntegerField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unisport_data.currency",
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "ordering": ["recommended_retail_price"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("order_by", models.SmallIntegerField()),
                ("stock_info", models.TextField(default="")),
                ("is_marketplace", models.BooleanField()),
                ("name_short", models.CharField(max_length=25)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="unisport_data.product",
                    ),
                ),
            ],
            options={
                "db_table": "stock",
            },
        ),
    ]
