# Generated by Django 3.0.3 on 2020-02-27 10:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('is_customizable', models.BooleanField(default=False)),
                ('relative_url', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='0', max_length=10)),
                ('product_main_image', models.URLField(max_length=255)),
                ('attribute_english', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('discount_type', models.CharField(max_length=50, null=True)),
                ('prices', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('currency', models.CharField(default='DKK', max_length=5)),
                ('delivery', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(max_length=255)),
                ('product_labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('online', models.BooleanField(default=True)),
                ('price_old', models.CharField(max_length=10)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('min_max_prices', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('image', models.URLField(max_length=255)),
                ('stock', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
