# Generated by Django 3.1 on 2020-08-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('image', models.URLField()),
                ('kids', models.BooleanField()),
            ],
        ),
    ]
