# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kids', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('delivery', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
