# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('kid_adult', models.CharField(max_length=1)),
                ('kids', models.CharField(max_length=1)),
                ('women', models.CharField(max_length=1)),
                ('free_porto', models.CharField(max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=20)),
                ('package', models.CharField(max_length=1)),
                ('delivery', models.CharField(max_length=20)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='test_app.Size'),
        ),
    ]
