# Generated by Django 2.1.1 on 2019-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customizable', models.BooleanField()),
                ('delivery', models.CharField(max_length=64)),
                ('kids', models.BooleanField()),
                ('name', models.CharField(max_length=64)),
                ('relative_url', models.CharField(max_length=128)),
                ('discount_percentage', models.FloatField()),
                ('kid_adult', models.BooleanField()),
                ('free_porto', models.BooleanField()),
                ('image', models.CharField(max_length=256)),
                ('sizes', models.CharField(max_length=512)),
                ('package', models.BooleanField()),
                ('price', models.FloatField()),
                ('discount_type', models.CharField(max_length=64)),
                ('product_labels', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('online', models.BooleanField()),
                ('price_old', models.FloatField()),
                ('currency', models.CharField(max_length=32)),
                ('img_url', models.CharField(max_length=256)),
                ('women', models.BooleanField()),
            ],
        ),
		# Ok this is pretty ass, if the database defaults to anything but unicode, it can not handle a lot of the
		# characters in the data set. So I a setting it manually here, even though there probably is a better way.
		# It should probably also be for the whole database, but this is the only table I need.
		migrations.RunSQL('alter table sportscrud_product convert to character set utf8 collate utf8_general_ci;'),
    ]

