# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=10)),
                ('women', models.CharField(max_length=10)),
                ('free_porto', models.CharField(max_length=10)),
                ('delivery', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online', models.CharField(max_length=10)),
                ('sizes', models.CharField(max_length=1000)),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kid_adult', models.CharField(max_length=20)),
                ('kids', models.CharField(max_length=10)),
                ('img_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('url', models.URLField()),
            ],
        ),
    ]
