# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.PositiveSmallIntegerField()),
                ('free_porto', models.PositiveSmallIntegerField()),
                ('delivery', models.CharField(max_length=20)),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online', models.PositiveSmallIntegerField()),
                ('women', models.PositiveSmallIntegerField()),
                ('sizes', models.CharField(max_length=150)),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kid_adult', models.PositiveSmallIntegerField()),
                ('kids', models.PositiveSmallIntegerField()),
                ('img_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
