# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161005_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.TextField(max_length=1000),
        ),
    ]
