# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161005_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free_porto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='kid_adult',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='online',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='women',
            field=models.IntegerField(),
        ),
    ]
