# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161005_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free_porto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='kid_adult',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='online',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='women',
            field=models.CharField(max_length=20),
        ),
    ]
