# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161006_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free_porto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='online',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='women',
            field=models.CharField(max_length=10),
        ),
    ]
