# Generated by Django 3.1.1 on 2020-09-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default='')),
                ('age', models.CharField(choices=[(1, 'Adults'), (2, 'Kids')], max_length=1)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=1)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
