# Generated by Django 3.1.1 on 2020-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='age',
            field=models.IntegerField(choices=[(1, 'Adults'), (2, 'Kids')], default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
