# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sizes', models.CharField(blank=True, default='', max_length=350)),
                ('delivery', models.CharField(blank=True, default='', max_length=150)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11)),
                ('url', models.URLField(blank=True, default='')),
                ('img_url', models.URLField(blank=True, default='')),
                ('kids', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('women', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('kid_adult', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('free_porto', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('package', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
