# Generated by Django 2.1.7 on 2019-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('is_customizable', models.BooleanField()),
                ('delivery', models.CharField(max_length=255)),
                ('kids', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('relative_url', models.CharField(max_length=255)),
                ('discount_percentage', models.IntegerField()),
                ('kid_adult', models.BooleanField()),
                ('free_porto', models.BooleanField()),
                ('image', models.CharField(max_length=255)),
                ('sizes', models.CharField(max_length=255)),
                ('package', models.BooleanField()),
                ('price', models.IntegerField()),
                ('discount_type', models.CharField(max_length=255)),
                ('product_labels', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('online', models.BooleanField()),
                ('price_old', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('women', models.BooleanField()),
            ],
        ),
    ]
