# Generated by Django 2.1.7 on 2019-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20190330_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='free_porto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_customizable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='online',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_old',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_labels',
        ),
        migrations.RemoveField(
            model_name='product',
            name='relative_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='women',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kid_adult',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
