# Generated by Django 2.1.7 on 2019-03-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20190330_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
    ]
