# Generated by Django 2.1.7 on 2019-03-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20190330_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
