# Generated by Django 2.1.7 on 2019-03-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_auto_20190330_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=100, max_length=255),
            preserve_default=False,
        ),
    ]
