# Generated by Django 2.1.7 on 2019-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_auto_20190331_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
    ]
