# Generated by Django 2.1.7 on 2019-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_auto_20190410_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
