# Generated by Django 4.0.6 on 2022-07-28 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unisport_id', models.CharField(max_length=6)),
                ('name', models.TextField()),
                ('relative_url', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('delivery', models.CharField(max_length=255)),
                ('online', models.BooleanField(default=False)),
                ('is_customizable', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock_quantity', models.IntegerField()),
                ('is_marketplace', models.BooleanField()),
                ('name_short', models.CharField(max_length=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unisport_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percentage', models.IntegerField()),
                ('recommended_retail_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unisport_app.currency')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unisport_app.product')),
            ],
        ),
    ]
