# Generated by Django 4.0.6 on 2022-07-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name_short',
            field=models.CharField(max_length=30),
        ),
    ]
