# Generated by Django 4.0.6 on 2022-07-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0002_alter_stock_name_short'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product_id', 'size'), name='unique product size'),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
