# Generated by Django 4.0.6 on 2022-07-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0003_stock_unique product size_alter_stock_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price__max_price']},
        ),
    ]
