# Generated by Django 4.0.6 on 2022-08-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unisport_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
