# Generated by Django 4.0.6 on 2022-08-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0005_alter_product_unisport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unisport_id',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
