# Generated by Django 4.0.6 on 2022-08-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0006_alter_product_unisport_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='unique product size',
        ),
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
    ]
