# Generated by Django 4.0.6 on 2022-08-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisport_app', '0007_remove_stock_unique product size_alter_stock_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product_id', 'size'), name='unique product size'),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
