# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(max_length=200)),
                ('free_porto', models.BooleanField()),
                ('img_url', models.CharField(max_length=500)),
                ('kid_adult', models.BooleanField()),
                ('kids', models.BooleanField()),
                ('name', models.CharField(max_length=500)),
                ('package', models.BooleanField()),
                ('price', models.FloatField()),
                ('price_old', models.FloatField()),
                ('sizes', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('women', models.BooleanField()),
            ],
        ),
    ]
