# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'products', '0001_initial'), (b'products', '0002_auto_20170227_0142'), (b'products', '0003_auto_20170227_0144'), (b'products', '0004_auto_20170227_0144'), (b'products', '0005_auto_20170227_0153'), (b'products', '0006_auto_20170227_0157'), (b'products', '0007_auto_20170227_0201'), (b'products', '0008_auto_20170227_2014'), (b'products', '0009_auto_20170227_2019'), (b'products', '0010_auto_20170301_0101'), (b'products', '0011_auto_20170301_0106'), (b'products', '0012_auto_20170301_0110'), (b'products', '0013_auto_20170301_0114'), (b'products', '0014_auto_20170301_0231')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='name')),
                ('is_customizable', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='customozable?')),
                ('delivery', models.CharField(max_length=50, verbose_name='delivery')),
                ('kids', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='kids')),
                ('kid_adult', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='kid adult')),
                ('product_id', models.IntegerField(blank=True, editable=False, null=True, verbose_name='product id')),
                ('free_porto', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='free porto')),
                ('image', models.URLField(blank=True, null=True, verbose_name='image')),
                ('package', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='package')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('sizes', models.TextField(default='One Size', verbose_name='Sizes')),
                ('online', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='online')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='image URL')),
                ('women', models.BooleanField(choices=[(True, '1'), (False, '0')], default=False, verbose_name='women')),
                ('currency', models.CharField(max_length=50, verbose_name='currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='old price')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'name')},
        ),
        migrations.AlterField(
            model_name='product',
            name='free_porto',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='free porto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='customozable?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kid_adult',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='kid adult'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='kids'),
        ),
        migrations.AlterField(
            model_name='product',
            name='online',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='product',
            name='women',
            field=models.BooleanField(choices=[(True, '1'), (False, '0')], verbose_name='women'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_porto',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='free porto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='customozable?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kid_adult',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='kid adult'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='kids'),
        ),
        migrations.AlterField(
            model_name='product',
            name='online',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='product',
            name='women',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='women'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.CharField(choices=[('True', '1'), ('False', '0')], default='0', max_length=1, verbose_name='customizable?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_porto',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='free porto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='customizable?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kid_adult',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='kid adult'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kids',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='kids'),
        ),
        migrations.AlterField(
            model_name='product',
            name='online',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='product',
            name='women',
            field=models.CharField(choices=[('1', 'True'), ('0', 'False')], default='0', max_length=1, verbose_name='women'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='old price'),
        ),
    ]
