# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('is_customizable', models.BooleanField(default='0', verbose_name='customozable?')),
                ('delivery', models.CharField(max_length=50, verbose_name='delivery')),
                ('kids', models.BooleanField(default='0', verbose_name='dids')),
                ('kid_adult', models.BooleanField(default='0', verbose_name='kid adult')),
                ('product_id', models.IntegerField(editable=False, verbose_name='product id')),
                ('free_porto', models.IntegerField(default='0', verbose_name='free porto')),
                ('image', models.URLField(verbose_name='image')),
                ('package', models.IntegerField(verbose_name='package')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('sizes', models.TextField(default='One Size', verbose_name='Sizes')),
                ('online', models.BooleanField(default='0', verbose_name='online')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='image URL')),
                ('women', models.BooleanField(default='0', verbose_name='women')),
                ('currency', models.CharField(max_length=50, verbose_name='currency')),
                ('unisport_id', models.CharField(max_length=50, verbose_name='unisport id')),
            ],
        ),
    ]
