# Generated by Django 3.1 on 2020-08-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
