# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_squashed_0014_auto_20170301_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
